services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=admin
      - APP_USER=gs
      - APP_USER_PASSWORD=gs123
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -s gs/gs123@//localhost:1521/XEPDB1"]
      interval: 30s
      timeout: 10s
      retries: 10

  gs-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gs-api
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=gs
      - SPRING_DATASOURCE_PASSWORD=gs123

volumes:
  oracle_data:
