version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: gs
      POSTGRES_PASSWORD: gs123
      POSTGRES_DB: safeguard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gs"]
      interval: 10s
      timeout: 5s
      retries: 5

  gs-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gs-api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/safeguard
      SPRING_DATASOURCE_USERNAME: gs
      SPRING_DATASOURCE_PASSWORD: gs123

volumes:
  postgres_data:
